# This file was generated by GoReleaser. DO NOT EDIT.
class Orninject < Formula
  desc "orninject is a template engine used to manage Docker images templates repositories."
  homepage "https://ornikar.github.io/orninject/"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ornikar/orninject/releases/download/v1.0.0/orninject_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "450657a62842493a746930f51f498d5eb73e0828c3294ef7fdc69cba5e166bd8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ornikar/orninject/releases/download/v1.0.0/orninject_1.0.0_Linux_x86_64.tar.gz"
      sha256 "c1258b4c648a2fb9884d7af9e59557465f961b047ee29c70f03e4161dfb38a71"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ornikar/orninject/releases/download/v1.0.0/orninject_1.0.0_Linux_arm64.tar.gz"
        sha256 "cddd5af7a3f762e597d4e78ac206bed4545af130a956716b6739a5aec8e4c204"
      else
        url "https://github.com/ornikar/orninject/releases/download/v1.0.0/orninject_1.0.0_Linux_armv6.tar.gz"
        sha256 "5aa1ed8dffd447205b155a59009271ee5d1436552d062be584870ebff1647d97"
      end
    end
  end

  def install
    bin.install "orninject"
  end

  test do
    system "orninject version"
  end
end
